server:
  port: 8050
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangpeiyong/spring-cloud-demo/
          search-paths: config-repo
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/